POST https://tech-test-rzw4.onrender.com/person
Content-Type: application/json

{
    "name": "Lucca",
    "email": "user123@gmail.com",
    "birth": "03/05/2020"
}

###
GET https://tech-test-rzw4.onrender.com/person

###
PATCH https://tech-test-rzw4.onrender.com/person/65a5bb551a6757f1df1d2a3a
Content-Type: application/json

{
    "name": "Vitor",
    "email": "user123@gmail.com",
    "birth": "03/05/2020"
}

###
DELETE https://tech-test-rzw4.onrender.com/person/65a5bb551a6757f1df1d2a3a
