POST https://tech-test-rzw4.onrender.com/person
Content-Type: application/json

{
    "name": "luzais",
    "email": "junior@gmail.com",
    "birth": "03052500"
}

###
GET https://tech-test-rzw4.onrender.com/person

###
PATCH https://tech-test-rzw4.onrender.com/person/65a4de589c574e53d0b1ac22
Content-Type: application/json

{
    "name": "Lucca4",
    "email": "lucca0403@gmail.com",
    "birth": "04032003"
}

###
DELETE https://tech-test-rzw4.onrender.com/person/65a4e9c9cb9d8d68c3f049bb
